[[constraint]]
  name = "code.cloudfoundry.org/cli"
  version = "6.42.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"

[prune]
  go-tests = true
  unused-packages = true
